"""create findings table

Revision ID: acc58b19a1ed
Revises: 7eab437e407d
Create Date: 2026-07-18 16:54:52.482319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc58b19a1ed'
down_revision: Union[str, None] = '7eab437e407d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('dollar_impact', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('suggested_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_org_id'), 'findings', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_org_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
