global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core-service:8081']

  - job_name: 'analysis-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['analysis-engine:8000']
